### PR TITLE
fix: adjust invalid namespace declaration to be compatible with Clojure 1.9.0-*

### PR DESCRIPTION
**Pull request by thenonameguy**

### CODE REVIEW

**Comment by thenonameguy** [comment]
We'll open our own fork for this library. I'll reopen another PR from that fork with the complete set of fixes.

**Comment by meredydd** [comment]
OK - I'd have accepted this as soon as I woke up, but feel free to give me a fuller PR :)

**Comment by thenonameguy** [comment]
Yeah, sadly this was not as trivial as it seemed at first. There's also something wrong with constructing unbound named functions, so we elided it for now. See the diff: https://github.com/meredydd/expect-call/compare/master...whitepages:master?expand=1
I'll clean the changes up and open another PR soon.

**Comment by meredydd** [comment]
Yeah; I'm not going to merge a PR changing the official upstream location :)

May I ask why you felt the need to create a full fork with a separate name and clojars repo?

**Comment by thenonameguy** [comment]
Because I needed this to be working ASAP in staging and we couldn't upgrade our codebase to the latest Clojure version because of the faulty code in this repo. Who knows when a public PR gets merged? :)

**Comment by meredydd** [comment]
Welp, looking at that diff, I'd be happy to take everything except the "`rebrand as whitepages`" commit. Looking forward to the updated PR.

**Comment by thenonameguy** [comment]
Yep, that's what I meant by cleaning up the changes. I also see a possibility to enhance the current codebase with clojure.spec features if we're ok to release a new version of this library with 1.9.0-RC1 support (thinking of macro form validation, easier parsing of mock-fns).

**Comment by meredydd** [comment]
That'd be neat. (I'd like to maintain backward compatibilities to versions that aren't still RC for now, but apart from that, PRs very welcome!)

**Pull request closed without merging**
